language: node_js

node_js:
  - "node"

dist: trusty

sudo: required

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

after_success:
  - yarn coverage